# Generated by Django 5.0.1 on 2024-01-22 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_auction_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 11, 36, 47, 776354)),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_account',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
