# Generated by Django 5.0.1 on 2024-01-20 13:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_auction_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 14, 49, 47, 521320)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='last_bid_user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
