# Generated by Django 5.0.1 on 2024-01-08 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auction_has_ended_auction_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pictrue',
            field=models.ImageField(default=datetime.datetime(2024, 1, 8, 17, 32, 56, 855205, tzinfo=datetime.timezone.utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 18, 32, 23, 197641)),
        ),
    ]
