# Generated by Django 5.0.1 on 2024-01-20 15:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_auction_duration_alter_auction_last_bid_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 16, 52, 28, 655042)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='last_bid_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='picture',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
