# Generated by Django 5.0.1 on 2024-01-08 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auction_min_bid_auction_price_alter_auction_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='price',
            new_name='start_price',
        ),
        migrations.AddField(
            model_name='auction',
            name='current_price',
            field=models.IntegerField(default=models.IntegerField(default=1)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 18, 49, 24, 474208)),
        ),
    ]
