# Generated by Django 5.0.1 on 2024-01-08 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_auction_current_price_alter_auction_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_price',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 18, 57, 33, 130694)),
        ),
    ]
