# Generated by Django 5.0.1 on 2024-01-08 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_auction_current_price_alter_auction_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 19, 10, 39, 30289)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='has_ended',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
