# Generated by Django 5.0.1 on 2024-01-14 12:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_auction_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='auction',
            name='items',
            field=models.ManyToManyField(related_name='auctions', to='base.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 13, 14, 46, 69412)),
        ),
    ]
