# Generated by Django 5.0.1 on 2024-01-14 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_auction_options_auction_items_item_host_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='pictrue',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='host',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='items',
        ),
        migrations.RemoveField(
            model_name='item',
            name='host',
        ),
        migrations.AlterField(
            model_name='auction',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 13, 20, 58, 976001)),
        ),
    ]
